### ISSUE TITLE
special request 

### ISSUE THREAD

**Issue by nesquik011** [stephomi/sculptgl#102]
hello , i want you to help me to add new tool or modifies old one with option ( talking about masking tool ) I want to function like put dot by dot on on the 3D model then once I close the dots it select area , like lasso tool in photoshop

**Comment by stephomi** [comment]
Sorry I don't maintain sculptgl anymore!

**Comment by nesquik011** [comment]
@stephomi  ok thank you , if you don't want to work anymore with the project , so kindly can you give me hints how to add that option ?

**Comment by stephomi** [comment]
I don't mind answering specific question but this one is too general/complex.
User input (interaction), rendering (the lasso), etc...

However, I can answer for the polygon/lasso thing:
- you need to triangulate the polygon, for example with https://github.com/mapbox/earcut
- optionally, you'll want to "simplify" the polygon beforehand, if you want to handle self-intersection (otherwise the triangulation might fail) https://github.com/junmer/clipper-lib
- then project all the vertices on screen and check if the point is inside the polygon (either with  point-inside-polygon test https://stackoverflow.com/a/29915728, or simply with a point-inside-triangle approach)

**Comment by nesquik011** [comment]
@stephomi great thank you a lot for respond  , how to finding shortest path using two points  on mesh ? cos expect any librabry or good algorithm, otherwise browser will crash with high cpu

**Comment by stephomi** [comment]
For that problem, you should probably look into A* algorithm.

It shouldn't be that expensive, but it depends of the mesh topology and polycount.

**Comment by stephomi** [comment]
For that problem, you should probably look into A* algorithm.
It shouldn't be that expensive, but it depends of the mesh topology and polycount.

By the way you should proably ignore my previous message on the lasso/polygon thing.
I though you wanted to draw the lasso in screenspace independently from the mesh (for example like the blender selection tool).

In that case you indeed need to know the shorted points between 2 vertices.
Once you got these path, and if your path is closed (important), simply tags all the vertices, and flood fill all the vertices inside.
It's a bit similar to this part https://github.com/stephomi/sculptgl/blob/605a58cb9e3ddcea35ce8c3d02e3b6a45034be36/src/math3d/Picking.js#L344-L372

**Comment by stephomi** [comment]
For that problem, you should probably look into A* algorithm.
It shouldn't be that expensive, but it depends of the mesh topology and polycount.

By the way you should proably ignore my previous message on the lasso/polygon thing.
I though you wanted to draw the lasso in screenspace independently from the mesh (for example like the blender selection tool).

In that case you indeed need to know the shorted points between 2 vertices.
Once you got these path, and if your path is closed (important), simply tags all the vertices, and flood fill all the vertices inside.
It's a bit similar to this part https://github.com/stephomi/sculptgl/blob/605a58cb9e3ddcea35ce8c3d02e3b6a45034be36/src/math3d/Picking.js#L344-L372

**Comment by stephomi** [comment]
For that problem, you should probably look into A* algorithm.
It shouldn't be that expensive, but it depends of the mesh topology and polycount.

By the way you should proably ignore my previous message on the lasso/polygon thing.
I though you wanted to draw the lasso in screenspace independently of the mesh (for example like the blender selection tool).

In that case you indeed need to know the shorted points between 2 vertices.
Once you got these path, and if your path is closed (important), simply tags all the vertices, and flood fill all the vertices inside.
It's a bit similar to this part https://github.com/stephomi/sculptgl/blob/605a58cb9e3ddcea35ce8c3d02e3b6a45034be36/src/math3d/Picking.js#L344-L372
