### ISSUE TITLE
Allow PWA functionality.

### ISSUE THREAD

**Issue by Julien-Peeters** [stephomi/sculptgl#103]
Allowing sculptGL to also be turned into a PWA, would make the life of quite a few people so much better. It allows for offline functionality, not internet dependent.
Here's [an article](https://www.optasy.com/blog/3-essential-steps-convert-your-website-progressive-web-app) I found on it and it's surprisingly easy.

**Comment by stephomi** [comment]
I've stopped maintaining sculptgl but I'm working actively on a (commercial) better native mobile version.
