### ISSUE TITLE
Wacom Pressure Sensitivity not working

### ISSUE THREAD

**Issue by ndee85** [stephomi/sculptgl#19]
I use a wacom Intuous 4.
Pen Pressure doesn't seem to work under windows 7.

**Comment by stephomi** [comment]
9a9f03c5d76707082fd8c854de121750b18a49c9 :(

**Comment by naomik** [comment]
so wacom can't be used now anymore? there's no way to enable it?

**Comment by disjukr** [comment]
@naomik chrome now supports [PointerEvent](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) (since chrome 55. current stable version is 56). so we can make sculptgl to support tablet pen pressure by using PointerEvent instead of NPAPI.

**Comment by stephomi** [comment]
Thanks for the heads up, didn't know it was released, I just added the support!

I don't have a wacom tablet, so I can't really test.
I tested on my nexus 5x, and it does have an impact, though the pressure is infered from the surface area rather than true pressure.
