### ISSUE TITLE
Change of the sculpting tools.

### ISSUE THREAD

**Issue by ebarranco** [stephomi/sculptgl#29]
When you are using the paint tool (or any other) and use the shortcut "c" to modify the intensity, the paint tool shift to the crease tool, every time. This happend only when you used the shortcut key.

**Comment by stephomi** [comment]
Ah good catch.
It happened because you still have the focus on the html select element.

Now it should be fixed :
https://github.com/stephomi/sculptgl/commit/cea8511c308a99c1b0fd81a826795a8ab7f5aaa4

**Comment by ebarranco** [comment]
It works fine now. thanks @stephomi
