### ISSUE TITLE
something doesn't work

### ISSUE THREAD

**Issue by irisred** [stephomi/sculptgl#32]
in your code which is for sketchfab, commit sha: 7dd7233af4, when I run the index.html page on my local server, sphere can't rotate when mousedown on the blank area and mousemove, but when I do this thing in https://labs.sketchfab.com/sculptfab/, the sphere can rotate.
how did this happen?

**Comment by stephomi** [comment]
sculptfab is a fork of sculptgl and it now lies here (it's kinda old though) : 
https://github.com/sketchfab/sculptgl/tree/master

**Comment by irisred** [comment]
I saw the master branch's code, I think the CSS files didn't update,  but mousemove in blank truly worked, anyway, it works, this is the most important
