### ISSUE TITLE
about the mouse thing

### ISSUE THREAD

**Issue by irisred** [stephomi/sculptgl#33]
I saw there was a circle at where the mouse moved or click, I use other controller to do the mouse thing, but could you tell me how to add the circle to my controller? there are the X-position and Y-position on the page of my controller, which part of the code add the circle at  the position? thanks

**Comment by stephomi** [comment]
It's here : https://github.com/stephomi/sculptgl/blob/master/src/mesh/Selection.js

It only displays the circle while we are picking the mesh. And if we sculpt, I only show the small dot.

**Comment by irisred** [comment]
I saw that, what about the sketchfab? where is the circle of it defined?  https://github.com/sketchfab/sculptgl

**Comment by stephomi** [comment]
Ah... it was different back then.
It was in the shader :
https://github.com/sketchfab/sculptgl/blob/master/shaders/reflection.frag#L17-L20

**Comment by irisred** [comment]
is the js function called "picking", or just loadshaders function load the .frag file? 
like here:https://github.com/sketchfab/sculptgl/blob/master/sculptgl.js#L186-L209
if I use another controller just like touch pen or Leap Motion, can the circle also be displayed?

**Comment by stephomi** [comment]
It's the shader that draw the circle...
It uses the center of the circle [here](https://github.com/sketchfab/sculptgl/blob/master/shaders/reflection.frag#L3)
And its radius [here](https://github.com/sketchfab/sculptgl/blob/master/shaders/reflection.frag#L6)

The picking is the stuffs that check what is under your cursor by casting a ray.
It's done [here](https://github.com/sketchfab/sculptgl/blob/master/sculptgl.js#L505) in the mousemove event.

Keep in mind that the sculptfab version is almost 2 years old and that I don't maintain it.
You should probably use the latest verson :).

**Comment by irisred** [comment]
okay, thanks for you reply and patience, I will try the latest version,
anyhow, thank you
