### ISSUE TITLE
Grid mark Box and double tap.

### ISSUE THREAD

**Issue by ebarranco** [stephomi/sculptgl#34]
The Show grid mark box does not update correctly, when you clear a scene.
The local/world camera view hardly detect the graphics tablets taps, it works fine with a mouse.

I show you in this video.  https://dl.dropboxusercontent.com/u/69554201/ScuptGLBug001.mp4

**Comment by stephomi** [comment]
Thanks for the detailed report !

I just solved the first issue : https://github.com/stephomi/sculptgl/commit/e131383e7e32489f18766c25477f21ac5cc6b0f6

As for the second issue, maybe https://github.com/stephomi/sculptgl/commit/4b6a8904545729e229996f8e36e200890b6cb30f is fixing it but I'm not sure. It works fine on my android though. Can you quickly re-test it ?

**Comment by ebarranco** [comment]
Definitely something have changed, now I have a rate of success of 50-50, half of the times, I can achieve it, and the other half, cannot.
