### ISSUE TITLE
Windows Standalone Version.

### ISSUE THREAD

**Issue by ebarranco** [stephomi/sculptgl#35]
I'm a linux user, but some are telling me that the standalone version of windows do not start. I looked for a windows machine and I can't use de win64 neither win32 version. ¿There's something wrong with these versions or I need install an extra functionality?

![fail](https://cloud.githubusercontent.com/assets/11136544/9800096/af382de0-57d0-11e5-8fce-b0448bb57593.png)

**Comment by stephomi** [comment]
Normally you don't have anything to do (as long as it also works on the web version).
At least it works fine on my windows.

To be honest, I generate the standalone builds automatically with https://github.com/nwjs/nw-builder.
So I don't really control what's going on precisely.

Maybe, I assume it might have something to do with https://github.com/nwjs/nw.js/wiki/Webgl-support-on-windows.

By the way, the web version is using a cache manifest, so if you are offline it should work fine.
It will only download some stuffs in case you are not up-to date
Normally... :)

**Comment by ebarranco** [comment]
Thanks, all of them are using the web version already. I told them about the dll's files and directX install but they don't seems to care much about it, now. I personally had curiosity, but neither of the solutions worked for me on the system that I borrowed.
