### ISSUE TITLE
From settings page, assigning a hotkey for brush mode does not work

### ISSUE THREAD

**Issue by combi** [stephomi/sculptgl#38]
Hello,
I tried to use the settings page to create a custom url, to configure the hotkeys.
If I try to assign a hotkey to brush, such as brush:b for example, it does not work.
Works fine for other commands though.

Nicolas

**Comment by stephomi** [comment]
Thanks for the report.
I just fixed it and the fix should be live now.

**Comment by combi** [comment]
Nice! Just tried and it works well!
Thanks

Nicolas

2016-06-20 20:30 GMT+02:00 Stéphane GINIER <notifications@github.com>:
