### ISSUE TITLE
Open scene file in web server directly by custom URL

### ISSUE THREAD

**Issue by ehipasika** [stephomi/sculptgl#41]
Can I add a custom URL in my 3d library preview page, and open the appointed model file just like:

 http://XXXXXXX.com/sculptgl? 
 *fileOpen/Importfile*+[file path in web server]

And what function should I call?

I would like to share 3d art work, and allow visitor to revise & co-creat it, I think it's funny, 

Thanks for awesome web app

**Comment by stephomi** [comment]
Yes it's possible, just done it in (00091d7ae5e284c88ee4cc131564effd1f37da26)

It supports the same filetype as the the gui, so ply/obj/stl/sgl.

The option is modelurl=url, for example http://stephaneginier.com/sculptgl/?modelurl=https://gist.githubusercontent.com/noonat/1131091/raw/3ef186720b1bb6e704c46aebf57a42677d1638af/cube.obj

The url should have cors enabled to allow download (github has it).
