### ISSUE TITLE
Where is index.html?

### ISSUE THREAD

**Issue by Yoshimaster96** [stephomi/sculptgl#44]
I cannot find a download for the index.html file. Where is it?

**Comment by stephomi** [comment]
The are in the [tool ](https://github.com/stephomi/sculptgl/tree/master/tools)directory.
If you use ``npm run dev``, it should move it to the app folder

**Comment by Yoshimaster96** [comment]
Which one do I open? There are two in the tool folder.

**Comment by stephomi** [comment]
It won't work if you open it directly, you have to build the project first.
Simply follow the readme!

```
npm install -g rollup # if not already done
npm install
npm run dev # and visit app/index.html
```

**Comment by ehipasika** [comment]
I try to deploy it to my local server according follow your guide, but after "npm run dev" node.js command prompt noticed that 'cp' isn't internal/external command, or execuction programme. and I check my system path, it have include node.js' command. Could you tell me how to solve this problem? I would like to debug the IOS browsers' issue.

**Comment by stephomi** [comment]
The command is
```
cp tools/index.dev.html app/index.html && rollup -cwm
```
^ It's in package.json. It just move index.dev.html into app/ folder and run rollup

**Comment by Yoshimaster96** [comment]
Why don't you include a pre-built version, to make it more accessible? Unless it's platform-dependent.

**Comment by stephomi** [comment]
Pre-built version needs to be updated regularly, also, there's both a minified and non-minified version.

The latest version of the code is always accessible through https://stephaneginier.com/sculptgl

I forgot that "cp" was a linux only command :), I develop on windows but I have mingw installed.
The script is dead simple though.

**Comment by ehipasika** [comment]
ok, I try to install minGW.

**Comment by stephomi** [comment]
You can also replace cp with copy :), it should work the same.

**Comment by ehipasika** [comment]
I‘ve try replace copy for cp and install mingw are also not work, I am using cygwin now, and manual enter command

**Comment by Raukk** [comment]
Related to this, I changed the scripts and got them running (I think), but I can't get the page to actually load.
I got to the point where the Command Line gave these messages:"
        1 file(s) copied.
        1 file(s) copied.
checking rollup-watch version...
bundling...
bundled in 3358ms. Watching for changes...
"

I have tried (in chrome): 'localhost', 'localhost/app/index.html', 'https://localhost/app/index.html', 'https://localhost', and 'file:///C:/Repos/sculptgl/app/index.html' 
All but the last one return "localhost refused to connect." and the last one doesn't work for the usual reasons.

Is it running on a non-standard port, or did I get Rollup stuck in a loop or something weird?

I'm running a standard Windows 10, I used the Node.js Command Prompt to issue 'npm run dev'.
If I get it working on stock Windows I'll commit it back as a second set of scripts.

**Comment by stephomi** [comment]
Like many js project, you have to setup a local server.
Easiest way to do is through python 2 with `python -m SimpleHTTPServer 8000` or with python 3 `python -m http.server 8000`

**Comment by Raukk** [comment]
> It's also easy to setup a quick local server with nodejs (I could also link it it up with the npm run dev...).

Thank you for the super fast reply.
I just assumed you had set it up with Node since you require it. I'll see if I can get the node server working even though I'm a Node Noob.
