### ISSUE TITLE
voxel remeshing

### ISSUE THREAD

**Issue by lomar75** [stephomi/sculptgl#45]
Hello.
Congratulations for the excellent work you have done.
When I do "voxel remeshing" creates an OBJ file to be 1k and not working.
I do not understand the issue.

**Comment by stephomi** [comment]
The "resolution slider" is not the polycount target (you can't set precisely the number of quads you target).

By not working, what did happen exactly?

**Comment by stephomi** [comment]
Indeed thanks for the report, I'll fix that.

**Comment by stephomi** [comment]
Fixed by https://github.com/stephomi/sculptgl/commit/96c509b4d10a6cc993c48f74119ddcb359ddcb5a!

**Comment by lomar75** [comment]
Thanks so much.
Now it's okay. very nice!!!
