### ISSUE TITLE
Alpha texture no longer work after new update

### ISSUE THREAD

**Issue by ehipasika** [stephomi/sculptgl#46]
Square/skin ahpla texture and import alpha tex image no longer work after your new update for the javascript es6.

**Comment by stephomi** [comment]
Arf thanks for the report, will fix that.

**Comment by stephomi** [comment]
Fixed by https://github.com/stephomi/sculptgl/commit/b9c1e30675f60ef9a6bdfc7f517a3f65d33f0aa6.
