### ISSUE TITLE
Delete object doesn't work as expected

### ISSUE THREAD

**Issue by celer** [stephomi/sculptgl#49]
So I've been trying to figure out how to delete an object, so I figured I'd hit the "delete" key, but that seems to delete the entire scene, I'd expect it to delete an object, and I'd also expect a similar menu item as well.

**Comment by stephomi** [comment]
I can't reproduce the issues.
If I add a cylinder, a cube, or load an obj, pressing the "delete" key only deletes the current selection.

If you have a way to reproduce, I'm interested (it's possible I merge the objects of an obj file for example, which might be the issue).
