### ISSUE TITLE
How to set  dynamic topology enabled by default

### ISSUE THREAD

**Issue by bobbychan** [stephomi/sculptgl#50]
I just know use "dynamicToggleActivate()" function to enabled  dynamic topology ,but i want to know that How to set  dynamic topology enabled by default
thanks.

**Comment by stephomi** [comment]
https://github.com/stephomi/sculptgl/blob/master/src/Scene.js#L539
^ adding in the first line
``
if(!mesh.isDynamic) mesh = new MeshDynamic(mesh);
``
