### ISSUE TITLE
Problems with masking in dynamic topology.

### ISSUE THREAD

**Issue by ebarranco** [stephomi/sculptgl#54]
The masking tool has an unexpected behaviour with dynamic topology,[ I tried to show you in this video.](https://www.dropbox.com/s/nnh8mgpyrjxwlpz/SculptGLMaskingBug.mp4)

**Comment by stephomi** [comment]
Thanks for the report.

Fixed by https://github.com/stephomi/sculptgl/commit/e08b44a4dfb0d593005f9681e12e480d5a080746

Decimation/subdivision is now dependent of masking.

**Comment by ebarranco** [comment]
It works pretty well now. Thank you.
