### ISSUE TITLE
top bar menus don't open in iOS

### ISSUE THREAD

**Issue by selfsame** [stephomi/sculptgl#55]
The top bar menus (File, Scene, etc.) won't open in iOS browsers.  (I've tried both chrome and safari apps)

the iOS version 10.3.1

Note: these menus do work with android

**Comment by stephomi** [comment]
Unfortunately I don't have an iOS browser so I can't fix easily the issue for now.
The ui is not really designed for mobile, the top bar was meant to be opened on hover, not on click, so it's actually surprising it's working on android.

I think android consider a touch as an hover but iOS don't.
Looks like something to do with https://stackoverflow.com/questions/35187970/css-hover-not-working-on-ios-safari-and-chrome

**Comment by selfsame** [comment]
yes an `onclick` attribute does fix this, closing this and opened an issue in [yagui](https://github.com/stephomi/yagui/issues/1)
