### ISSUE TITLE
Location and Size of the object are changed after Remeshing

### ISSUE THREAD

**Issue by krisnotepad** [stephomi/sculptgl#59]
SculptGL is pretty good and It's easy to use.
However I found the REMSHE not work as expect. When the object has been remeshed , the location and the size of the object  are changed. 
If the object is exported to stl, the size of the object is changed imported by SculptGL, both the size and the location are changed by other softwares, such as blender.

**Comment by stephomi** [comment]
Did you uncheck Files -> Import -> **scale and center**?

**Comment by krisnotepad** [comment]
Oh, I see it. This option will scale an center imported objects.

**Comment by stephomi** [comment]
Yup, it was mainly to avoid tricky case if you import an huge model and a tiny model

You can set a default url option to disable it https://stephaneginier.com/sculptgl/?scaleCenter=0

**Comment by krisnotepad** [comment]
But the location and the szie of the exported object is still be changed if it has been remeshed.

**Comment by stephomi** [comment]
Indeed looks like : 
- stl export is not keeping the scale, nor the position
- obj export is keep the scale but not the correct position
- ply export is keeping both scale and position correctly

I'll try to check when I have time.

**Comment by stephomi** [comment]
It should work better now (https://github.com/stephomi/sculptgl/commit/bbac4ced484d7bdf3d086d6aa2c9f058758176a5)

Don't really have time to test it thoroughly, so I hope I didn't break anything

**Comment by krisnotepad** [comment]
CooI! It works now. Thank you.
