### ISSUE TITLE
Feature request: run as mobile web-app

### ISSUE THREAD

**Issue by ReinhardClaus** [stephomi/sculptgl#60]
Hi there, with these 2 tags added to the sculptGL app page:

```
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
```

sculptGl could be added as a full screen app to the Android/Apple home screen and would open without the address bar/tabs.

I think that would be very nice. Thanks for considering!

**Comment by ebarranco** [comment]
I read here about using SculptGL in android but I remember that I tried some time ago and it wasn't possible to work. Now it is possible, and it's great! have this would be nice. We need all the workspace available.

**Comment by stephomi** [comment]
Sure I'll see about the tags

**Comment by ReinhardClaus** [comment]
Thanks a lot for adding those. Great job on this awesome app btw!
