### ISSUE TITLE
The option [Scale and center] will change the real size of imported objects

### ISSUE THREAD

**Issue by krisnotepad** [stephomi/sculptgl#61]
When the option **Scale and center** is set, not only the view size of the imported object is resized, but also its data is changed.
The size of the objects is indeed resized.

**Comment by stephomi** [comment]
Yep this option is directly rescaling and moving the object itself.
The idea was that if you imported several meshes with different size or position, they are all consistently scaled/positioned.

**Comment by krisnotepad** [comment]
Oh! I see. Thank you.
