### ISSUE TITLE
sculptgl i try install but not work

### ISSUE THREAD

**Issue by nicejava** [stephomi/sculptgl#65]
stephomi .. i try follow your above but not work please explain step by step i use last code your update not have index.html , nmp install it's worked but nmp run dev not work !! show this below , i use appserv is webserver

copy tools/index.dev.html app/index.html && copy tools/authSuccess.html app/au
hSuccess.html && webpack -w

he syntax of the command is incorrect.
pm ERR! code ELIFECYCLE
pm ERR! errno 1
pm ERR! SculptGL@0.9.0 dev: copy tools/index.dev.html app/index.html && copy t ols/authSuccess.html app/authSuccess.html && webpack -w
pm ERR! Exit status 1
pm ERR!
pm ERR! Failed at the SculptGL@0.9.0 dev script.
pm ERR! This is probably not a problem with npm. There is likely additional log
ing output above.

pm ERR! A complete log of this run can be found in:
pm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2018-04-24T1
_19_46_003Z-debug.log

Show like this .. thanks

**Comment by nicejava** [comment]
try npm install -g webpack it show this (try in node.js command prompt)

C:\AppServ\www\sculptgl-master>npm -g webpack

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Administrator\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.6.0 C:\Program Files\nodejs\node_modules\npm

Did you mean this?
    pack

C:\AppServ\www\sculptgl-master>

**Comment by nicejava** [comment]
Now step try this
1. keep all file in localhost directory
2. open command prompt of node.js and move localhost directory
3. type npm install -g webpack (this is completed)
4. try type npm run dev (this is error like this below)

C:\AppServ\www\sculptgl-master>npm run dev

> SculptGL@0.9.0 dev C:\AppServ\www\sculptgl-master
> copy tools/index.dev.html app/index.html && copy tools/authSuccess.html app/au
thSuccess.html && webpack -w

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! SculptGL@0.9.0 dev: `copy tools/index.dev.html app/index.html && copy t
ools/authSuccess.html app/authSuccess.html && webpack -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the SculptGL@0.9.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-04-25T0
9_32_22_928Z-debug.log

C:\AppServ\www\sculptgl-master>

**Comment by stephomi** [comment]
`copy tools\\index.dev.html app\\index.html && copy tools\\authSuccess.html app\\authSuccess.html && webpack -w`

You changed the cp command by copy (which is windows only) so it needs those backslahes.

**Comment by nicejava** [comment]
That worked !! thanks 
but i'm try .obj face after imported it's not show face on program but it show balloon circle, Why not ?

**Comment by stephomi** [comment]
hmm can you paste a screenshot, not sure what a balloon circle is 🎈

**Comment by nicejava** [comment]
![image](https://user-images.githubusercontent.com/6760497/39238939-c074ff9e-48a9-11e8-8575-4512891ffef5.png)

actually this .obj is face

**Comment by nicejava** [comment]
Oh it's worked i will clear scene first .. thanks you

**Comment by stephomi** [comment]
Ah I see, importing new geometries indeed add them to the scene instead of replacing it.

**Comment by nicejava** [comment]
Thank you stephomi you're excellent

**Comment by nicejava** [comment]
Thank you stephomi you're excellent , How to edit program should be solved what files ? i need remove 
REDENRING , TOPOLOGY , SCULTING & PAINTING

**Comment by stephomi** [comment]
I probably can't help you further, the rest is purely programming, you'll have to dig it yourself.
