### ISSUE TITLE
PBR question. 

### ISSUE THREAD

**Issue by oivio** [stephomi/sculptgl#72]
Is there a way to render PBR on the background as well? And I cant find out how to add HDR images. Maybe someone can guide me?

PS: Thank you Stéphane for this amazing script!

**Comment by stephomi** [comment]
There is no way to add an HDR image at the moment, same for the background.

**Comment by oivio** [comment]
To bad. But, I did not give up yet. I am trying to go around that by changing canvas background to be transparent but, I have no idea on what I should look at. Since there is basically toons of lines of code.  I am only aware that I have to place **gl.clearColor(0, 0, 0, 0);** before **gl.clear(gl.COLOR_BUFFER_BIT);**. 

```
  gl.clearColor(0, 0, 0, 0);
  gl.clear(gl.COLOR_BUFFER_BIT);
```

Iv noticed this bit is in Scene.js but, looks like it does not work.

**Comment by stephomi** [comment]
Added an option do display the env on the background https://github.com/stephomi/sculptgl/commit/eb2854afb84fe98ee2de8bcd9f8aecc2c89a8019

Still no option to upload a custom HDR (it would require a prefiltering pass like https://placeholderart.wordpress.com/2015/07/28/implementation-notes-runtime-environment-map-filtering-for-image-based-lighting/...)
