### ISSUE TITLE
Add option to select/manipulate multiple objects

### ISSUE THREAD

**Issue by chuuko** [stephomi/sculptgl#73]
It's really annoying that I can't translate a mesh that has its eyes as separate objects. Please add an option to select multiple objects

**Comment by oivio** [comment]
There is an option to select multiple objects. You have to press alt+LMB but, to make it work after selecting a few objects you have to merge them ( Scene -> Merge Selection)

**Comment by nicejava** [comment]
Not have Scene -> Merge Selection .. where is this menu ?

**Comment by oivio** [comment]
> Not have Scene -> Merge Selection .. where is this menu ?

Iv made a mistake. To select items to merge you should press  SHIFT+LMB and click on the items to merge. Then you should see in the top toolbar in menu "Scene" an option "Merge Selection"

**Comment by makc** [comment]
@oivio when ever I press SHIFT I get this:
![Screen Shot 2019-09-25 at 16 59 49 ](https://user-images.githubusercontent.com/242577/65613260-fc828e80-dfb5-11e9-9d95-5a5e2cd98c97.png)

**Comment by stephomi** [comment]
For multiple selection, it's best to select the "darken unselected" option in the "Scene" folder to understand what's going on.

Shift is also a shortcut for smooth tool but you can simply ignore that.

**Comment by makc** [comment]
@stephomi I see. Well, with the E tool, even if the mesh is not darkened, it does not move, so in this context multiselection appears to be useless

**Comment by stephomi** [comment]
Yes, the transform tool is ignoring the multiple selection.
I'm doing a quick check to see if I can add it (but the multiple mesh thingy is super hacky in sculptgl)

**Comment by stephomi** [comment]
Done in https://github.com/stephomi/sculptgl/commit/089dfe29419198066ed2181f230b2e247d9cbb3c
