### ISSUE TITLE
Saving all and go to Sketchfab does not seem to work?

### ISSUE THREAD

**Issue by enzyme69** [stephomi/sculptgl#76]
I tried saving PBR and also trying the Sketchfab option but there seems to be no way to save Texture Albedo, Roughness, Metalness, etc?

Can we also have option like Dirty Vertex and AO output? Or I just use Blender for it?

**Comment by stephomi** [comment]
Sculptgl doesn't author textures, only vertex painting.
So basically, there is no way to export reliably the rough/metal painting information (the albedo information should work fine though).
