### ISSUE TITLE
orbiting when zoomed in (touch ui)

### ISSUE THREAD

**Issue by specularity** [stephomi/sculptgl#77]
When sculpting on a tablet, a problem i'm often having is that there's no way of orbiting the view when being zoomed in (when the model is filling the whole screen). I would have to zoom out and start a drag gesture from the background area which is distracting.

Zooming and Panning works zoomed in because it requires a two finger gesture. 

Can I suggest a possible solution for orbiting when zoomed in - This would be a "zoom/pan with two fingers then let go of one finger to orbit" gesture. 

Sounds a little crazy but I think it would work well enough because currently this only starts a draw stroke where it is not required.

**Comment by stephomi** [comment]
Thanks for the suggestion, note that I'm not really active anymore on sculptgl.
Nevertheless the solution seemed smart and easy to implement, so I tried to do it https://github.com/stephomi/sculptgl/commit/cc6279f3fb7cb547f50990cae4657369344dd675.

**Comment by stephomi** [comment]
You can also rotate by using 3 fingers, but it'll probably go crazy when releasing several fingers at once     so I don't really advise for it.

**Comment by specularity** [comment]
😮 wow works exactly like I was hoping for. Thanks very much for this early chritsmas gift. With a bluetooth keyboard this so much more usable than zBrush now for basic sculpting. Great project& good time to give it some rest, seems really finished for what it is.
