### ISSUE TITLE
WebGL version on ios browser camera bug

### ISSUE THREAD

**Issue by Sojtin** [stephomi/sculptgl#78]
I tried http://stephaneginier.com/sculptgl/ on ipad and first time i touch the screen on sphere drawing is working but after that every touch/swipe turning camera only.
Same story on every refresh.
Tried on every camera mode, and browsers: safari, firefox, chrome, aloha.

**Comment by stephomi** [comment]
Thanks for the report, it's probably a bug introduced with my latest change, I'll try to make a fix when I have time.

**Comment by craigastewart** [comment]
Same issue on iPad Air 2. I also tried other browsers but nothing works, first touch draws successfully but subsequent touches only rotate camera. Love this app so look forward to a fix!

**Comment by stephomi** [comment]
Is the issue fixed on one of these two links?
https://stephaneginier.com/archive/iostest/
https://stephaneginier.com/archive/iostest?forcereset=0

**Comment by PedramK2** [comment]
Hi,
Just tested on iPad Pro on iOS 12.11 and problem is still present on safari, chrome, Firefox

**Comment by stephomi** [comment]
Argh I made an error, I updated the link, could you try again? 🤞

**Comment by craigastewart** [comment]
Hi Stéphane, 

Just tested on my iPad 2 Air - the first link works but rotation is not smooth, swiping works for a second then you have to swipe again several times to continue camera rotation. The second link does not work.

Thanks for looking into this!

Craig

**Comment by craigastewart** [comment]
Yup! Both links appear to be working for me now! Thanks!

Craig

**Comment by stephomi** [comment]
Thanks for testing!

Fixed by https://github.com/stephomi/sculptgl/commit/87c651401a142a1bc2abcc5850988dbf0e763fd1
