### ISSUE TITLE
Baking vertex paint onto UV texture?

### ISSUE THREAD

**Issue by oivio** [stephomi/sculptgl#81]
This is just a small question, maybe request? Let's say we have a model with UV. After painting with vertex paint. Is there a possibility to export that painted textures into separate let's say jpg, png image file? 
The idea comes from that your brilliant script has already UV jpg, png files. I was just wondering if that would be possible to export that paint into image files :)

**Comment by stephomi** [comment]
Yes that's possible, but UVs are discarded when you use voxel remeshing or dynamic topology

**Comment by stephomi** [comment]
Done in https://github.com/stephomi/sculptgl/commit/1a03e1a2ee060cd15bd47bcf3fcaaf1f13f080eb
