### ISSUE TITLE
Performing Boolean Operation

### ISSUE THREAD

**Issue by xyzdcgan** [stephomi/sculptgl#82]
Hello, i  want to perform boolean operation on stl/obj files can you help me on that. i saw editsdf which you created and in which boolean op are done, as there is no original source code how can i integrate and use/perform boolean op in sculptgl.

**Comment by disjukr** [comment]
editsdf isn't mesh modeling tool.
but https://github.com/evanw/csg.js/ would be helpful

**Comment by xyzdcgan** [comment]
How we can use that in sculptgl tool directly, means how to convert mesh to csg. as boolean operation can be performed in csg format.

**Comment by disjukr** [comment]
need to implement that feature in sculptgl with csg.js

**Comment by xyzdcgan** [comment]
> need to implement that feature in sculptgl with csg.js

Can you guide me for implementing that, or provide any demo for that. 
Any help would be great.

**Comment by stephomi** [comment]
Thanks for your interest, but I'm not really active anymore on sculptgl, unless for bug fixes.

That being said I couldn't help myself to experiment a little bit with 2 (very) quick and dirty implementation:
- with csg and boolean remesh: https://github.com/stephomi/sculptgl/tree/booleanCSG
- with the voxel remesh (grid sdf): https://github.com/stephomi/sculptgl/tree/booleanRemesh

Both branch are working but I probably won't polish it as it requires more work to really integrate it.

* CSG branch
I'm using https://github.com/evanw/csg.js/ for csg.
Unsurprisingly, it's super slow, ~30s for 2 meshes of only 1k vertices.
From what I can see the resulting topology can have T junction, so in this states you can't sculpt anymore.
![csg](https://user-images.githubusercontent.com/4750281/51406053-475f2300-1b58-11e9-811a-f435baeb0fcd.jpg)
 
* Voxel remesh grid sdf branch
Similar to the current sculptgl remeshing functions (with same caveats, aka resampling/uniform topo)
![voxelgrid](https://user-images.githubusercontent.com/4750281/51407395-14b72980-1b5c-11e9-9268-11dc21a49aa4.jpg)

> editsdf isn't mesh modeling tool.

True, it's just an experiment.
However it's easy to produce a mesh from SDF tree (simply evaluate the sdf on a grid and then running marching cubes, like the voxel remesh). That's the whole UI/UX work that's hard...

**Comment by stephomi** [comment]
No easy solution for a robust boolean operator features on polygonal mesh.
It's certainly possible to get something faster but... I don't think we'll see a fast and robust (enough) implementation in javascript for this kind of problem.
Maybe in the C++ realm you can find alternative... but probably a pain to turn into wasm and performance/robustness might be still an issue (CGAL?, https://github.com/gilbo/cork?)

http://www.meshmixer.com/ can do boolean operation and it's fast, looks like it's using a threshold to detect intersection.

**Comment by xyzdcgan** [comment]
Yes @stephomi conversion is difficult and also not so sure that it will increase the speed of operation, surely will look into meshmixer for using threshold to increase speed of operation in csg. Thanks once again.
