### ISSUE TITLE
Deleting/Erase  extra element from mesh,

### ISSUE THREAD

**Issue by xyzdcgan** [stephomi/sculptgl#83]
Hello, @stephomi 
After subtraction two mesh the output we get is like 
![screenshot from 2019-02-06 15-50-26](https://user-images.githubusercontent.com/44637302/52335270-fc824e00-2a27-11e9-9c51-c974b088c976.png)

I only want to remove the part which is circled in black, is there any function which can perform this kind of operation.

Thank You.

**Comment by stephomi** [comment]
Very far from optimal but you could reuse the remesh function by using the difference operator (with a cube for example) https://github.com/stephomi/sculptgl/blob/1b67bdd369435b3436b6f6670d40da23d6d477fe/src/editing/Remesh.js#L370

Otherwise you need a custom algorithm to isolate this part before deleting it (picking the surface -> get a vert/tri -> iterate on the neighbors until everything is tagged and delete everything)

**Comment by xyzdcgan** [comment]
Thankyou, i was trying the custom method through predefined 
getVertexinradius() etc, of face,color,material. 
method and other and then trying to remove those from original vertex through getvertex(), 
after that calling remesh method which takes those new modified vertex,face,color,material.  

So now will try with remesh function to remove that and use difference operator

**Comment by stephomi** [comment]
The custom method would look like:

```javascript
var nbVertices = mesh.getNbVertices();
var vAr = mesh.getVertices();
var fAr = mesh.getFaces();

var vrvStartCount = mesh.getVerticesRingVertStartCount();
var vertRingVert = mesh.getVerticesRingVert();
var ringVerts = vertRingVert instanceof Array ? vertRingVert : null;

var vertTagFlags = mesh.getVerticesTagFlags();

var pickedVertices = new Uint32Array(nbVertices);
var acc = 1;
for (var i = 0; i < acc; ++i) {
    var id = pickedVertices[i];
    var start, end;
    if (ringVerts) {
        vertRingVert = ringVerts[id];
        start = 0;
        end = vertRingVert.length;
    } else {
        start = vrvStartCount[id * 2];
        end = start + vrvStartCount[id * 2 + 1];
    }

    for (var j = start; j < end; ++j) {
        var idv = vertRingVert[j];
        if (vertTagFlags[idv] === tagFlag)
            continue;
        vertTagFlags[idv] = tagFlag;
        pickedVertices[acc++] = idv;
    }
}

var fdelete = mesh.getFacesFromVertices(pickedVertices.subarray(0, acc));
var faces = new Uint32Array(4 * mesh.getNbFaces());
acc = 0;
for (i = 0; i < fdelete.length; ++i) {
    faces[fdelete[i] * 4] = Utils.TRI_INDEX;
}
for (i = 0; i < mesh.getNbFaces(); ++i) {
    var i4 = i * 4;
    if (faces[i4] === Utils.TRI_INDEX) {
        faces[acc * 4] = fAr[i4];
        faces[acc * 4 + 1] = fAr[i4];
        faces[acc * 4 + 2] = fAr[i4];
        faces[acc * 4 + 3] = fAr[i4];
        acc++
    }
}
faces = faces.subarray(0, acc);

var newMesh = new MeshStatic(mesh.getGL());
newMesh.setID(mesh.getID());
newMesh.setFaces(faces);
// unused verts will be pruned by "optimize"?
newMesh.setVertices(vertices);
if (colors) newMesh.setColors(colors);
if (materials) newMesh.setMaterials(materials);
newMesh.setRenderData(mesh.getRenderData());
newMesh.init();
newMesh.initRender();
return newMesh;```

**Comment by xyzdcgan** [comment]
@stephomi  Nice of you for providing the sample code for erasing extra element from mesh, i had a doubt regarding where to integrate this code either in remesh.js or any other class. Once Again Thanks :+1: :+1:
