### ISSUE TITLE
Please add support for splat maps & 256+ texture layers!!!

### ISSUE THREAD

**Issue by Thundros** [stephomi/sculptgl#84]
Hi, 1st off I'd like to say this is a PHENOMENAL work of art! Congratulations on your success! PLEASE keep up the excellent, EXCELLENT work! <3 Secondly, I'd like to request the ability if not already possible, in order to allow for splat maps to be used on heightmaps in order to change the detail to extremely high detail for each texture painted on to Terrain & allow for the use of 256+ texture layers with alpha in order to create an extremely high res Terrain with the exporting ability to export what was drawn ( INCLUDING the texture details ) to an OBJ file.

Once again, I'd like to thank you & CONGRATULATE you for the INCREDIBLE work! Please keep up the great work!

**Comment by stephomi** [comment]
Hi and thanks!

Sorry but I'm not really active anymore on sculptgl (except for small changes or bug fixes).
And splat map would be too long to implement (also not sure it'd make sense for

**Comment by Thundros** [comment]
...
