### ISSUE TITLE
WebGL GUI Dependency

### ISSUE THREAD

**Issue by xyzdcgan** [stephomi/sculptgl#86]
Hi @stephomi 
Can we Import/Export STL file without having GUI scene?
I have tried to use custom GL programatically but I think its not getting expected response while export STL file.
Dose sculptGL strictly depends on GUI OR we can call operations on mesh through programming ?

Thanks.

**Comment by stephomi** [comment]
It doesn't depend "strictly" on GUI, it shouldn't be hard to decouple it completely (some shortcuts/events are a bit linked to the GUI though).

Importing/Exporting to STL should be fine.

> I have tried to use custom GL programatically but I think its not getting expected response while export STL file.

If you still have issues, you can paste a snippet of code.

**Comment by xyzdcgan** [comment]
Thanks as you told i was able to do operation without GUI. @stephomi
