### ISSUE TITLE
How to import multi obj and merge combined into one obj

### ISSUE THREAD

**Issue by nicejava** [stephomi/sculptgl#88]
How to import multi obj and merge combined into one obj
such as import other eye obj and combine with on background face obj .. thank you

**Comment by stephomi** [comment]
https://stephaneginier.com/sculptgl/?outline=1&darkenUnselected=1
You can select multiple object by holding the "shift" key, then you have the choice : 
- scene -> mege selection
- topology -> voxel remeshing
