### ISSUE TITLE
Scale size of object changes after remesh operation.

### ISSUE THREAD

**Issue by xyzdcgan** [stephomi/sculptgl#89]
Hello @stephomi ,

After performing subtract operation on object the scaling size changes.
I checked the previous issue of scaling and checked that scale and centre option is disabled. 
Also checked that all commit are there in our clone which you gave in previous post.

https://github.com/stephomi/sculptgl/commit/bbac4ced484d7bdf3d086d6aa2c9f058758176a5

All these code is there in our clone.

Demo of issue.

We have added two 3d model, 
1) Square with Triangle 
2) Cylinder

When we load original model, its setting proper with its size and scale.

![Original3dModel](https://user-images.githubusercontent.com/44637302/56031510-5d3a4980-5d3d-11e9-8122-571de475d4d0.png)

Once we applied subtract operation (Square - Cylinder), The subtracted square's scale has been updated

![Subtracted3DModel](https://user-images.githubusercontent.com/44637302/56031539-6fb48300-5d3d-11e9-9f85-f5d36504c722.png)

Can you please look into this issue and if provide a solution or a way of how we can solve the issue.

Thanks, @stephomi

**Comment by stephomi** [comment]
Yes it's a known issue related to remeshing, it's not specific to substraction.

I've added a commit to booleanRemesh, it should be much better
Itttps://github.com/stephomi/sculptgl/commit/206f2ab1aea358b57ce4bf899288223ba157b659

Maybe I'll add it to master at some point, it's still not perfect though, at worse you can probably have an offset error as big as the cell size.

**Comment by xyzdcgan** [comment]
Thank you @stephomi  checking the commit.
